### ISSUE TITLE
Do not store a temporary file

### ISSUE THREAD

**Issue by julien-c** [davidefiocco/streamlit-fastapi-model-serving#11]
Great article and tutorial @davidefiocco!

Just a tiny detail but I'm pretty sure you can just send the binary data from the image using https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.Image.tobytes and a raw `starlette.Response`

Would love to read more about those subjects in the future!

**Comment by davidefiocco** [comment]
Hi @julien-c ! Thanks for your interest and feedback.

That's a good point, those tempfiles would eventually accumulate and crash the container... 

Following your suggestion, I tried as a possibly better solution:

```
bytes_io = io.BytesIO()
segmented_image.save(bytes_io, format='PNG')
return Response(bytes_io.getvalue(), media_type="image/png")
```

Let me know if this looks OK or you have better options in mind: I avoided using `to_bytes` because it returns the raw image data from the internal storage, and in my attempts the annotated image didn't render fine in the FastAPI documentation page.

**Comment by julien-c** [comment]
Oh yeah, looks perfect that way.

**Comment by davidefiocco** [comment]
Cool! I updated the post https://davidefiocco.github.io/2020/06/27/streamlit-fastapi-ml-serving.html accordingly, and I am closing this.

Thanks again @julien-c , indeed that'd be great to keep the content coming, let's see how it goes! :)
